server:
  port: 8081
#spring:
#  application:
#    name: product-service

#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  mapper-locations: com/gaoqi/mapper/xml/*.xml
